In [1]:
import numpy as np
import pandas as pd

In [3]:
flats = pd.read_csv('flats_cleaned.csv')
houses = pd.read_csv('house_cleaned.csv')

In [5]:
df = pd.concat([flats,houses],ignore_index=True)

In [7]:
df = df.sample(df.shape[0],ignore_index=True)

In [9]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 90 Gurgaon,flat,dlf regal gardens,1.30,7150.0,1818.0,Super Built up area 1818(168.9 sq.m.)Built Up ...,3,3,3+,not available,"Sector 90 Gurgaon, Gurgaon, Haryana",7.0,South,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",Located in the popular residential address of ...,NaN,"['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4.5 out ..."
1,3 BHK Flat in Sector 72 Gurgaon,flat,tata primanti,3.25,10545.0,3082.0,Super Built up area 3300(306.58 sq.m.),3,3,3,servant room,"Sector 72 Gurgaon, Gurgaon, Haryana",2.0,South,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",This is a meticulously designed 3 bhk apartmen...,NaN,"['Centrally Air Conditioned', 'High Ceiling He...","['Green Area4 out of 5', 'Construction4 out of..."
2,4 Bedroom House for sale in Dhankot,house,independent,0.70,9722.0,720.0,Plot area 80(66.89 sq.m.),4,3,2,"pooja room,store room","Dhankot, Gurgaon, Haryana",3.0,West,1 to 5 Year Old,NaN,Ground floor tuition center with computer lab ...,"['1 Fan', '1 Exhaust Fan', '1 Geyser', '1 Ligh...","['Feng Shui / Vaastu Compliant', 'Water Storage']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,2 BHK Flat in Sector 37D Gurgaon,flat,ramprastha the edge towers,0.80,5797.0,1380.0,Super Built up area 1380(128.21 sq.m.)Built Up...,2,2,3,not available,"Gurgaon, Sector 37D Gurgaon, Gurgaon, Haryana",2.0,North-East,1 to 5 Year Old,"['MDS Public School', 'St Pauls School', 'Sunc...","Club pool facing, \nOn 2nd floor,\nPremium fla...","['5 Fan', '2 Geyser', '7 Light', '2 Wardrobe',...","['Security / Fire Alarm', 'Intercom Facility',...","['Management3.5 out of 5', 'Green Area4 out of..."
4,3 BHK Flat in Sector 79 Gurgaon,flat,m3m golf hills phase 1,1.70,10828.0,1570.0,Built Up area: 1570 (145.86 sq.m.)Carpet area:...,3,2,3,not available,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",10.0,NaN,undefined,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",Best in class property available at sector 79 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."

In [11]:
df.shape

(3961, 20)

In [12]:
df.to_csv('gurgaon_properties.csv',index=False)